### ISSUE TITLE
ValueError: Number of channels in the input image and reference image must match!

### ISSUE THREAD

**Issue by BigFatherJesus** [volotat/SD-CN-Animation#104]
For the last 3 days, I have been getting this error when trying to use txt2vid, when I use vid2vid it works fine, I've tried reinstalling the extension, updating, or even rolling back to an older version of the extension but I can't seem to get rid of the issue, my guess is that it has to do with Controllnet but I am unable to verify.

It starts out fine but after the first few (2-3) frames it stops and I get greeted by the error.

# System Logs:

> INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  6.33it/s]
> Total progress: 15it [00:12,  1.18it/s]
> INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  6.97it/s]
> Total progress: 15it [00:02,  6.75it/s]
> INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  7.36it/s]
> Total progress: 100%|██████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  6.25it/s]
> INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.<00:00,  8.10it/s]
> 100%|████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  7.38it/s]
> Total progress: 100%|████████████████████████████████████████████████████████████████████| 6/6 [00:01<00:00,  5.02it/s]
> An exception occurred while trying to process the frame: Number of channels in the input image and reference image must match!
> Traceback (most recent call last):
>   File "C:\Users\.....\Desktop\AI\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\base_ui.py", line 141, in process
>     yield from txt2vid.start_process(*args)
>   File "C:\Users\.....\Desktop\AI\stable-diffusion-webui\extensions\SD-CN-Animation\scripts\core\txt2vid.py", line 169, in start_process
>     processed_frame = skimage.exposure.match_histograms(processed_frame, init_frame, channel_axis=-1)
>   File "C:\Users\.....\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\skimage\_shared\utils.py", line 406, in fixed_func
>     return func(*args, **kwargs)
>   File "C:\Users\.....\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\skimage\_shared\utils.py", line 348, in fixed_func
>     return func(*args, **kwargs)
>   File "C:\Users\.....\Desktop\AI\stable-diffusion-webui\venv\lib\site-packages\skimage\exposure\histogram_matching.py", line 69, in match_histograms
>     raise ValueError('Number of channels in the input image and '
> ValueError: Number of channels in the input image and reference image must match!

![image](https://github.com/volotat/SD-CN-Animation/assets/44375417/295c9a52-c5b9-4b00-993c-c3d78d8c06b4)

**Comment by volotat** [comment]
@BigFatherJesus I just updated the code, it should fix your issue, please check it out.

**Comment by BigFatherJesus** [comment]
@volotat I am still getting the exact same error, thanks for the fast response!

**Comment by volotat** [comment]
@BigFatherJesus My bad. I missed one another line where channels should be truncated. Try again please.

**Comment by BigFatherJesus** [comment]
@volotat Thanks for the prompt response! Everything works again now, thanks a lot! Great extension btw!
