### ISSUE TITLE
Fix integration with Vladmandic/automatic

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [volotat/SD-CN-Animation#46]
Because of deprecated gradio usage, this extension won't work with Vladmandic/automatic. See related issue: https://github.com/vladmandic/automatic/issues/817

Could you collaborate?

**Comment by BinaryQuantumSoul** [comment]
Related issue: https://github.com/volotat/SD-CN-Animation/issues/40#issue-1700467808

**Comment by BlastedRemnants** [comment]
I'm not sure if you're using Vlad's or Auto's, but for me it's working on Auto's with Commit: 5ab7f213.

**Comment by JoBilert** [comment]
I tried it with Vlad's and it threw a bunch of errors with the UI. When the UI eventually loads, there are double Menu-Entries and the whole UI is unresponsive until I manually move the Extension from the extensions-folder and restart Stable-Diffusion

**Comment by Averytingwong** [comment]
Same issue as Jobilert, had to remove it when using Vlad, spits out a ton of random stuff in console and gui becomes unresponsive.

**Comment by spiritform** [comment]
mine works in vlad but i do get error messages for every frame it generates...

Running script before postprocess batch: H:\AI\vlad1111\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: TypeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ H:\AI\vlad1111\automatic\modules\scripts.py:388 in postprocess_batch                                                                                                                                 │
│                                                                                                                                                                                                      │
│   387 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                                                                                       │
│ > 388 │   │   │   │   script.postprocess_batch(p, *args, images=images, **kwargs)                                                                                                                    │
│   389 │   │   │   except Exception as e:                                                                                                                                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Script.postprocess_batch() missing 1 required positional argument: 'enabled'
Running script before postprocess batch: H:\AI\vlad1111\automatic\extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py: TypeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ H:\AI\vlad1111\automatic\modules\scripts.py:388 in postprocess_batch                                                                                                                                 │
│                                                                                                                                                                                                      │
│   387 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                                                                                       │
│ > 388 │   │   │   │   script.postprocess_batch(p, *args, images=images, **kwargs)                                                                                                                    │
│   389 │   │   │   except Exception as e:                                                                                                                                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Script.postprocess_batch() missing 8 required positional arguments: 'enabled', 'mimic_scale', 'threshold_percentile', 'mimic_mode', 'mimic_scale_min', 'cfg_mode', 'cfg_scale_min', and
'powerscale_power'
Running script postprocess: H:\AI\vlad1111\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: TypeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ H:\AI\vlad1111\automatic\modules\scripts.py:380 in postprocess                                                                                                                                       │
│                                                                                                                                                                                                      │
│   379 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                                                                                       │
│ > 380 │   │   │   │   script.postprocess(p, processed, *args)                                                                                                                                        │
│   381 │   │   │   except Exception as e:                                                                                                                                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
Running script postprocess: H:\AI\vlad1111\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py: TypeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ H:\AI\vlad1111\automatic\modules\scripts.py:380 in postprocess                                                                                                                                       │
│                                                                                                                                                                                                      │
│   379 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                                                                                       │
│ > 380 │   │   │   │   script.postprocess(p, processed, *args)                                                                                                                                        │
│   381 │   │   │   except Exception as e:                                                                                                                                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Script.postprocess() missing 1 required positional argument: 'enabled'
Running script postprocess: H:\AI\vlad1111\automatic\extensions-builtin\sd-extension-steps-animation\scripts\steps_animation.py: TypeError
┌───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────┐
│ H:\AI\vlad1111\automatic\modules\scripts.py:380 in postprocess                                                                                                                                       │
│                                                                                                                                                                                                      │
│   379 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                                                                                       │
│ > 380 │   │   │   │   script.postprocess(p, processed, *args)                                                                                                                                        │
│   381 │   │   │   except Exception as e:                                                                                                                                                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Script.postprocess() missing 11 required positional arguments: 'is_enabled', 'codec', 'interpolation', 'duration', 'skip_steps', 'debug', 'run_incomplete', 'tmp_delete', 'out_create',
'tmp_path', and 'out_path'

**Comment by volotat** [comment]
Please, check out if the problem still relevant in new version.

**Comment by spiritform** [comment]
thanks! is there an easy way to update without having to reinstall?

**Comment by volotat** [comment]
@spiritform  Press "Check for updates" and then "Apply and restart UI" in the 'Extensions' tab.

**Comment by JoBilert** [comment]
Installed the latest version. Responsive WebUI at first but then errors and double menue entries again. To my layman's eye it seems like there are some lists/arrays that don't calculate the dimensions correctly when (certain) other extensions are installed, but that is just me wildguessing.

**Comment by spiritform** [comment]
yeah, i get the same errors, but it still works so all good!

**Comment by JoBilert** [comment]
> yeah, i get the same errors, but it still works so all good!

sadly doesn't work for me.. the first try of txt2vid crashed the webui

**Comment by Averytingwong** [comment]
UI still freezes for me as well.

**Comment by volotat** [comment]
The issue should be resolved now. Please try it again on the latest version.

**Comment by JoBilert** [comment]
Tried the lasted version, still getting an immensely long error message.  :( Hard for me to locate the source.

**Comment by volotat** [comment]
@JoBilert Could you show the last several lines of it?

**Comment by JoBilert** [comment]
OK, here is what I did:

1. Launched vlad
2. Installed SD_CNB from Extensions tab
3. Updated all Extensions
4. Applied and Restart
-> No error at restart

Then I change into the SD-CN Tab and my console shows the following:

```bash
Traceback (most recent call last):
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1318, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1221, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1196, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 274, received: 2).
Wanted outputs:
    [dropdown, slider, slider, dropdown, checkbox, checkbox, slider, slider, checkbox, checkbox, colorpicker, checkbox, slider, slider, checkbox, radio, checkboxgroup, slider, slider, slider, checkbox, textbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, checkbox, textbox, textbox, checkbox, checkbox, textbox, checkbox, checkbox, checkbox, slider, checkbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, slider, checkbox, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, slider, radio, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, radio, checkbox, checkbox, checkbox, dropdown, checkboxgroup, slider, slider, slider, slider, checkbox, checkbox, slider, checkbox, slider, slider, radio, slider, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, number, number, checkbox, checkbox, number, checkbox, checkbox, slider, slider, slider, number, checkboxgroup, slider, checkbox, checkbox, checkbox, textbox, dropdown, slider, number, number, textbox, dropdown, dropdown, dropdown, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, slider, textbox, textbox, dropdown, textbox, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, radio, radio, number, checkboxgroup, dropdown, slider, slider, radio, slider, slider, slider, slider, number, checkbox, radio, radio, slider, checkbox, checkbox, slider, checkbox, slider, checkbox, checkbox, checkbox, checkbox, radio, slider, slider, dropdown, dropdown, slider, checkbox, radio, textbox, textbox, textbox, textbox, textbox, slider, slider, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, number, number, number, checkbox, number, checkbox, checkbox, dropdown, checkbox, textbox, textbox, slider, slider, textbox, dropdown, dropdown, code, checkbox, textbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, dropdown, checkbox, slider, checkbox, checkbox, textbox, checkbox, textbox, dropdown, textbox, number, textbox, textbox, textbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, checkbox, checkbox, dropdown, slider]
Received outputs:
    [{'value': 'anything-v4.5.safetensors [1d1e459f9f]', 'choices': ['15_woopwoopPhoto_12.safetensors [fee5b01364]', 'anything-v4.5.safetensors [1d1e459f9f]', 'avalonTruvision_v2.safetensors [71f4dfd701]', 'babes_11.safetensors [79886b6484]', 'berryMix_v1.ckpt [d9691ffffe]', 'chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]', 'classicAnim-v1.ckpt [93d2772039]', 'Deliberate-inpainting.safetensors [cb15a7187a]', 'deliberate_v2.safetensors [9aba26abdf]', 'dreamlikePhotoRealV2_dreamlikePhotoRealV2.safetensors [92970aa785]', 'dreamshaper_5Bakedvae.safetensors [a60cfaa90d]', 'FAD-foto-assisted-diffusion_V0.safetensors [edb5d5a587]', 'ghostmix_v12.safetensors [f20c91bd27]', 'hasdx_realisticHASDX.safetensors [801a3c06ce]', 'illuminatiDiffusionV1_v11.safetensors [cae1bee30e]', 'instruct-pix2pix-00-22000.safetensors [fbc31a67aa]', 'M4RV3LSDUNGEONSV10_mD10.safetensors [700c7ac788]', 'neverendingDreamNED_bakedVae.safetensors [64b14b6ca5]', 'noiseOffsetForTrue_v10.safetensors [a2750866f9]', 'openjourneyAkaMid..._v1.ckpt [5d5ad06cc2]', 'protogenX53OfficialR_10.safetensors [e3cda540bf]', 'providence_2111Anchor.safetensors [af725d64ad]', 'realisticVisionV20_v20-inpainting.safetensors [b19fee4ab1]', 'revAnimated_v11-inpainting.safetensors [2b6dda3d4b]', 'revAnimated_v11.safetensors [d725be5d18]', 'riffusionTxt2Audio_riffusionTxt2Audio.ckpt', 'RPG-v4.safetensors [e04b020012]', 'samDoesSexyBlend_safetensor.safetensors [171c237b86]', 'sd-v1-5-inpainting.ckpt [c6bbc15e32]', 'uberRealisticPornMerge_urpmv13.safetensors [f93e6a50ac]', 'unvailAI3DKXV2_3dkxV2.safetensors [d10ad6063d]', 'v1-5-pruned-emaonly.ckpt [cc6cb27103]', 'v2-1_768-ema-pruned.ckpt [ad2a33c361]', 'vectorArt_vectorArtBeta.safetensors [f0f94c95d1]', 'wd-1-4-anime_e2.ckpt [c76e0962bc]'], '__type__': 'generic_update'}, "{"sd_model_checkpoint": "anything-v4.5.safetensors [1d1e459f9f]", "sd_checkpoint_cache": 0, "sd_vae_checkpoint_cache": 0, "sd_vae": "Automatic", "stream_load": false, "model_reuse_dict": false, "inpainting_mask_weight": 1.0, "initial_noise_multiplier": 1, "img2img_color_correction": false, "img2img_fix_steps": false, "img2img_background_color": "#ffffff", "enable_quantization": true, "comma_padding_backtrack": 20, "CLIP_stop_at_last_layers": 2, "upcast_attn": false, "cross_attention_optimization": "Scaled-Dot-Product", "cross_attention_options": [], "sub_quad_q_chunk_size": 512, "sub_quad_kv_chunk_size": 512, "sub_quad_chunk_threshold": 80, "always_batch_cond_uncond": false, "temp_dir": "", "clean_temp_dir_at_start": true, "ckpt_dir": "E:\\ImageAI\\models", "vae_dir": "E:\\ImageAI\\automatic\\models\\VAE", "embeddings_dir": "E:\\ImageAI\\automatic\\models\\embeddings", "hypernetwork_dir": "E:\\ImageAI\\automatic\\models\\hypernetworks", "codeformer_models_path": "E:\\ImageAI\\automatic\\models\\Codeformer", "gfpgan_models_path": "E:\\ImageAI\\automatic\\models\\GFPGAN", "esrgan_models_path": "E:\\ImageAI\\automatic\\models\\ESRGAN", "bsrgan_models_path": "E:\\ImageAI\\automatic\\models\\BSRGAN", "realesrgan_models_path": "E:\\ImageAI\\automatic\\models\\RealESRGAN", "scunet_models_path": "E:\\ImageAI\\automatic\\models\\ScuNET", "swinir_models_path": "E:\\ImageAI\\automatic\\models\\SwinIR", "ldsr_models_path": "E:\\ImageAI\\automatic\\models\\LDSR", "clip_models_path": "E:\\ImageAI\\automatic\\models\\CLIP", "lora_dir": "E:\\ImageAI\\automatic\\models\\Lora", "lyco_dir": "E:\\ImageAI\\automatic\\models\\LyCORIS", "styles_dir": "styles.csv", "samples_save": true, "samples_format": "jpg", "samples_filename_pattern": "", "save_images_add_number": true, "grid_save": false, "grid_format": "jpg", "grid_extended_filename": true, "grid_only_if_multiple": true, "grid_prevent_empty_spots": true, "n_rows": -1, "save_txt": false, "save_log_fn": "", "save_images_before_face_restoration": true, "save_images_before_highres_fix": true, "save_images_before_color_correction": true, "save_mask": false, "save_mask_composite": false, "jpeg_quality": 85, "webp_lossless": false, "img_max_size_mp": 200, "use_original_name_batch": true, "use_upscaler_name_as_suffix": true, "save_selected_only": true, "save_init_img": false, "save_to_dirs": false, "grid_save_to_dirs": false, "use_save_to_dirs_for_ui": false, "directories_filename_pattern": "[date]", "directories_max_prompt_words": 8, "outdir_samples": "", "outdir_txt2img_samples": "outputs/text", "outdir_img2img_samples": "outputs/image", "outdir_extras_samples": "outputs/extras", "outdir_grids": "", "outdir_txt2img_grids": "outputs/grids", "outdir_img2img_grids": "outputs/grids", "outdir_save": "outputs/save", "outdir_init_images": "outputs/init-images", "memmon_poll_rate": 2, "precision": "Autocast", "cuda_dtype": "FP16", "no_half": false, "no_half_vae": false, "upcast_sampling": false, "disable_nan_check": true, "rollback_vae": false, "opt_channelslast": false, "cudnn_benchmark": false, "cuda_allow_tf32": true, "cuda_allow_tf16_reduced": true, "cuda_compile": false, "cuda_compile_mode": "none", "cuda_compile_verbose": true, "cuda_compile_errors": true, "disable_gc": false, "upscaler_for_img2img": "SwinIR_4x", "realesrgan_enabled_models": ["R-ESRGAN 4x+", "R-ESRGAN 4x+ Anime6B"], "ESRGAN_tile": 192, "ESRGAN_tile_overlap": 8, "SCUNET_tile": 256, "SCUNET_tile_overlap": 8, "use_old_hires_fix_width_height": false, "dont_fix_second_order_samplers_schedule": false, "ldsr_steps": 100, "ldsr_cached": false, "SWIN_tile": 192, "SWIN_tile_overlap": 8, "face_restoration_model": "CodeFormer", "code_former_weight": 0.2, "face_restoration_unload": false, "unload_models_when_training": false, "pin_memory": true, "save_optimizer_state": false, "save_training_settings_to_txt": true, "dataset_filename_word_regex": "", "dataset_filename_join_string": " ", "embeddings_templates_dir": "E:\\ImageAI\\automatic\\train/templates", "training_image_repeats_per_epoch": 1, "training_write_csv_every": 0, "training_enable_tensorboard": false, "training_tensorboard_save_images": false, "training_tensorboard_flush_every": 120, "interrogate_keep_models_in_memory": false, "interrogate_return_ranks": true, "interrogate_clip_num_beams": 1, "interrogate_clip_min_length": 32, "interrogate_clip_max_length": 192, "interrogate_clip_dict_limit": 2048, "interrogate_clip_skip_categories": ["artists", "movements", "flavors"], "interrogate_deepbooru_score_threshold": 0.65, "deepbooru_sort_alpha": false, "deepbooru_use_spaces": false, "deepbooru_escape": true, "deepbooru_filter_tags": "", "extra_networks_default_view": "cards", "extra_networks_default_multiplier": 1.0, "extra_networks_card_width": 0, "extra_networks_card_height": 0, "extra_networks_add_text_separator": " ", "sd_hypernetwork": "None", "sd_lyco": "None", "sd_lora": "None", "gradio_theme": "derekzen/stardust", "return_grid": true, "return_mask": false, "return_mask_composite": false, "disable_weights_auto_swap": true, "send_seed": false, "send_size": true, "font": "", "keyedit_precision_attention": 0.1, "keyedit_precision_extra": 0.05, "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()", "quicksettings": "sd_model_checkpoint,sd_vae,initial_noise_multiplier", "hidden_tabs": ["Vector Studio", "Model Converter", "Train", "System Info"], "ui_tab_reorder": "From Text, From Image, Process Image", "ui_scripts_reorder": "Enable Dynamic Thresholding, ControlNet", "ui_reorder": "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts", "ui_extra_networks_tab_reorder": "", "show_progressbar": true, "live_previews_enable": true, "show_progress_grid": true, "notification_audio_enable": false, "notification_audio_path": "html/notification.mp3", "show_progress_every_n_steps": 2, "show_progress_type": "Approx NN", "live_preview_content": "Combined", "live_preview_refresh_period": 250, "show_samplers": ["Euler", "DPM++ 2M", "DPM++ 2S a Karras", "DPM++ 2S a", "DPM++ SDE Karras", "DPM2 a Karras", "Euler a", "DPM++ 2M Karras", "UniPC", "DPM++ SDE", "DPM2 Karras"], "fallback_sampler": "Euler a", "eta_ancestral": 1.0, "eta_ddim": 0.0, "ddim_discretize": "uniform", "s_churn": 0.0, "s_min_uncond": 0, "s_tmin": 0.0, "s_noise": 1.0, "eta_noise_seed_delta": 31336, "always_discard_next_to_last_sigma": false, "uni_pc_variant": "bh1", "uni_pc_skip_type": "time_uniform", "uni_pc_order": 3, "uni_pc_lower_order_final": true, "token_merging": false, "token_merging_ratio": 0.5, "token_merging_hr_only": true, "token_merging_ratio_hr": 0.5, "token_merging_random": false, "token_merging_merge_attention": true, "token_merging_merge_cross_attention": false, "token_merging_merge_mlp": false, "token_merging_maximum_down_sampling": 1, "token_merging_stride_x": 2, "token_merging_stride_y": 2, "postprocessing_enable_in_main_ui": [], "postprocessing_operation_order": [], "upscaling_max_images_in_cache": 5, "disabled_extensions": [], "disable_all_extensions": "none", "sd_checkpoint_hash": "1d1e459f9f549a404746390de21df33b8c8134f863b3b5da7d784843e782900a", "aesthetic_scorer_enabled": true, "aesthetic_scorer_clip_model": "ViT-L/14", "control_net_model_config": "models\\cldm_v15.yaml", "control_net_model_adapter_config": "models\\t2iadapter_sketch_sd14v1.yaml", "control_net_detectedmap_dir": "detected_maps", "control_net_models_path": "", "control_net_modules_path": "", "control_net_max_models_num": 5, "control_net_model_cache_size": 1, "control_net_no_detectmap": false, "control_net_detectmap_autosaving": false, "control_net_allow_script_control": false, "control_net_sync_field_args": false, "controlnet_show_batch_images_in_ui": false, "controlnet_increment_seed_during_batch": false, "image_browser_active_tabs": "txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others", "image_browser_hidden_components": [], "image_browser_with_subdirs": true, "image_browser_preload": false, "image_browser_copy_image": false, "image_browser_delete_message": true, "image_browser_txt_files": true, "image_browser_debug_level": "0 - none", "image_browser_delete_recycle": false, "image_browser_scan_exif": true, "image_browser_mod_shift": false, "image_browser_mod_ctrl_shift": false, "image_browser_enable_maint": true, "image_browser_ranking_pnginfo": false, "image_browser_page_columns": 6.0, "image_browser_page_rows": 6.0, "image_browser_pages_perload": 20.0, "image_browser_use_thumbnail": false, "image_browser_thumbnail_size": 200.0, "image_browser_swipe": false, "image_browser_img_tooltips": true, "image_browser_scoring_type": "aesthetic_score", "image_browser_show_progress": true, "infzoom_outpath": "outputs", "infzoom_outSUBpath": "infinite-zooms", "infzoom_outsizeW": 512, "infzoom_outsizeH": 512, "infzoom_ffprobepath": "", "infzoom_txt2img_model": null, "infzoom_inpainting_model": null, "infzoom_defPrompt": "{\n        \"prePrompt\": \"Huge spectacular Waterfall in \",\n        \"prompts\": {\n
      \"data\": [\n                        [0, \"a dense tropical forest\"],\n                        [2, \"a Lush jungle\"],\n                        [3, \"a Thick rainforest\"],\n                        [5, \"a Verdant canopy\"]\n                ]\n        },\n        \"postPrompt\": \"epic perspective,(vegetation overgrowth:1.3)(intricate, ornamentation:1.1),(baroque:1.1), fantasy, (realistic:1) digital painting , (magical,mystical:1.2) , (wide angle shot:1.4), (landscape composed:1.2)(medieval:1.1),(tropical forest:1.4),(river:1.3) volumetric lighting ,epic, style by Alex Horley Wenjun Lin greg rutkowski Ruan Jia (Wayne Barlowe:1.2)\",\n        \"negPrompt\": \"frames, border, edges, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur, bad-artist\"\n}", "infzoom_collectAllResources": false, "sadtalker_result_dir": "E:\\ImageAI\\automatic\\outputs\\SadTalker", "openpose3d_use_online_version": false, "arh_javascript_aspect_ratio_show": true, "arh_javascript_aspect_ratio": "1:1, 3:2, 4:3, 5:4, 16:9", "arh_ui_javascript_selection_method": "Aspect Ratios Dropdown", "arh_hide_accordion_by_default": false, "arh_expand_by_default": false, "arh_ui_component_order_key": "MaxDimensionScaler, PredefinedAspectRatioButtons, PredefinedPercentageButtons", "arh_show_max_width_or_height": true, "arh_max_width_or_height": 1024, "arh_show_predefined_aspect_ratios": true, "arh_predefined_aspect_ratio_use_max_dim": false, "arh_predefined_aspect_ratios": "1:1, 4:3, 16:9, 9:16, 21:9", "arh_show_predefined_percentages": true, "arh_predefined_percentages": "25, 50, 75, 125, 150, 175, 200", "arh_predefined_percentages_display_key": "Incremental/decremental percentage (-50%, +50%)", "def_img_cfg": "1.5", "training_picker_fixed_size": 512.0, "training_picker_videos_path": "E:\\ImageAI\\automatic\\training-picker\\videos", "training_picker_framesets_path": "E:\\ImageAI\\automatic\\training-picker\\extracted-frames", "training_picker_default_output_path": "E:\\ImageAI\\automatic\\training-picker\\cropped-frames", "dp_ignore_whitespace": false, "dp_write_raw_template": false, "dp_write_prompts_to_file": false, "dp_parser_variant_start": "{", "dp_parser_variant_end": "}", "dp_parser_wildcard_wrap": "__", "dp_limit_jinja_prompts": false, "dp_auto_purge_cache": false, "dp_magicprompt_default_model": "Gustavosta/MagicPrompt-Stable-Diffusion", "dp_magicprompt_batch_size": 1}"]
```
-> Vlad show Errors all over in Browser

-> Shut down console and Browser-Tab and restart

on startup I get:

```bash
16:29:12-675147 ERROR    Calling script:
                         E:\ImageAI\automatic\extensions\sd-webui-aspect-ratio-helper\scripts\sd_webui_aspect_ratio_help                         er.py/ui: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ E:\ImageAI\automatic\modules\scripts.py:245 in wrap_call                                                             ││                                                                                                                      ││   244 │   try:                                                                                                       ││ ❱ 245 │   │   res = func(*args, **kwargs)                                                                            ││   246 │   │   return res                                                                                             ││                                                                                                                      ││ E:\ImageAI\automatic\extensions\sd-webui-aspect-ratio-helper\aspect_ratio_helper\main.py:54 in ui                    ││                                                                                                                      ││   53 │   │   │   │   # the visible property on each component to hide them.                                          ││ ❱ 54 │   │   │   │   component.render()                                                                              ││   55                                                                                                                 ││                                                                                                                      ││                                               ... 2 frames hidden ...                                                ││                                                                                                                      ││ E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py:265 in set_event_trigger                                ││                                                                                                                      ││    264 │   │   │   "trigger": event_name,                                                                            ││ ❱  265 │   │   │   "inputs": [block._id for block in inputs],                                                        ││    266 │   │   │   "outputs": [block._id for block in outputs],                                                      ││                                                                                                                      ││ E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py:265 in <listcomp>                                       ││                                                                                                                      ││    264 │   │   │   "trigger": event_name,                                                                            ││ ❱  265 │   │   │   "inputs": [block._id for block in inputs],                                                        ││    266 │   │   │   "outputs": [block._id for block in outputs],                                                      │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: 'NoneType' object has no attribute '_id'
```
and then:

```bash
Traceback (most recent call last):
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1318, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1221, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\ImageAI\automatic\venv\lib\site-packages\gradio\blocks.py", line 1196, in validate_outputs
    raise ValueError(
ValueError: An event handler didn't receive enough output values (needed: 274, received: 2).
Wanted outputs:
    [dropdown, slider, slider, dropdown, checkbox, checkbox, slider, slider, checkbox, checkbox, colorpicker, checkbox, slider, slider, checkbox, radio, checkboxgroup, slider, slider, slider, checkbox, textbox, checkbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, checkbox, textbox, textbox, checkbox, checkbox, textbox, checkbox, checkbox, checkbox, slider, checkbox, textbox, checkbox, checkbox, checkbox, checkbox, checkbox, slider, checkbox, number, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, textbox, slider, radio, radio, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, radio, checkbox, checkbox, checkbox, dropdown, checkboxgroup, slider, slider, slider, slider, checkbox, checkbox, slider, checkbox, slider, slider, radio, slider, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, number, number, checkbox, checkbox, number, checkbox, checkbox, slider, slider, slider, number, checkboxgroup, slider, checkbox, checkbox, checkbox, textbox, dropdown, slider, number, number, textbox, dropdown, dropdown, dropdown, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, slider, textbox, textbox, dropdown, textbox, textbox, textbox, textbox, checkbox, checkbox, checkbox, checkbox, textbox, slider, radio, radio, number, checkboxgroup, dropdown, slider, slider, radio, slider, slider, slider, slider, number, checkbox, radio, radio, slider, checkbox, checkbox, slider, checkbox, slider, checkbox, checkbox, checkbox, checkbox, radio, slider, slider, dropdown, dropdown, slider, checkbox, radio, textbox, textbox, textbox, textbox, textbox, slider, slider, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, dropdown, checkbox, checkbox, checkbox, checkbox, checkbox, checkbox, number, number, number, checkbox, number, checkbox, checkbox, dropdown, checkbox, textbox, textbox, slider, slider, textbox, dropdown, dropdown, code, checkbox, textbox, checkbox, checkbox, textbox, dropdown, checkbox, checkbox, dropdown, checkbox, slider, checkbox, checkbox, textbox, checkbox, textbox, dropdown, textbox, number, textbox, textbox, textbox, checkbox, checkbox, checkbox, textbox, textbox, textbox, checkbox, checkbox, dropdown, slider]
Received outputs:
    [{'value': '15_woopwoopPhoto_12.safetensors [fee5b01364]', 'choices': ['15_woopwoopPhoto_12.safetensors [fee5b01364]', 'anything-v4.5.safetensors [1d1e459f9f]', 'avalonTruvision_v2.safetensors [71f4dfd701]', 'babes_11.safetensors [79886b6484]', 'berryMix_v1.ckpt [d9691ffffe]', 'chilloutmix_NiPrunedFp32Fix.safetensors [fc2511737a]', 'classicAnim-v1.ckpt [93d2772039]', 'Deliberate-inpainting.safetensors [cb15a7187a]', 'deliberate_v2.safetensors [9aba26abdf]', 'dreamlikePhotoRealV2_dreamlikePhotoRealV2.safetensors [92970aa785]', 'dreamshaper_5Bakedvae.safetensors [a60cfaa90d]', 'FAD-foto-assisted-diffusion_V0.safetensors [edb5d5a587]', 'ghostmix_v12.safetensors [f20c91bd27]', 'hasdx_realisticHASDX.safetensors [801a3c06ce]', 'illuminatiDiffusionV1_v11.safetensors [cae1bee30e]', 'instruct-pix2pix-00-22000.safetensors [fbc31a67aa]', 'M4RV3LSDUNGEONSV10_mD10.safetensors [700c7ac788]', 'neverendingDreamNED_bakedVae.safetensors [64b14b6ca5]', 'noiseOffsetForTrue_v10.safetensors [a2750866f9]', 'openjourneyAkaMid..._v1.ckpt [5d5ad06cc2]', 'protogenX53OfficialR_10.safetensors [e3cda540bf]', 'providence_2111Anchor.safetensors [af725d64ad]', 'realisticVisionV20_v20-inpainting.safetensors [b19fee4ab1]', 'revAnimated_v11-inpainting.safetensors [2b6dda3d4b]', 'revAnimated_v11.safetensors [d725be5d18]', 'riffusionTxt2Audio_riffusionTxt2Audio.ckpt', 'RPG-v4.safetensors [e04b020012]', 'samDoesSexyBlend_safetensor.safetensors [171c237b86]', 'sd-v1-5-inpainting.ckpt [c6bbc15e32]', 'uberRealisticPornMerge_urpmv13.safetensors [f93e6a50ac]', 'unvailAI3DKXV2_3dkxV2.safetensors [d10ad6063d]', 'v1-5-pruned-emaonly.ckpt [cc6cb27103]', 'v2-1_768-ema-pruned.ckpt [ad2a33c361]', 'vectorArt_vectorArtBeta.safetensors [f0f94c95d1]', 'wd-1-4-anime_e2.ckpt [c76e0962bc]'], '__type__': 'generic_update'}, "{"sd_model_checkpoint": "15_woopwoopPhoto_12.safetensors [fee5b01364]", "sd_checkpoint_cache": 0, "sd_vae_checkpoint_cache": 0, "sd_vae": "Automatic", "stream_load": false, "model_reuse_dict": false, "inpainting_mask_weight": 1.0, "initial_noise_multiplier": 1, "img2img_color_correction": false, "img2img_fix_steps": false, "img2img_background_color": "#ffffff", "enable_quantization": true, "comma_padding_backtrack": 20, "CLIP_stop_at_last_layers": 2, "upcast_attn": false, "cross_attention_optimization": "Scaled-Dot-Product", "cross_attention_options": [], "sub_quad_q_chunk_size": 512, "sub_quad_kv_chunk_size": 512, "sub_quad_chunk_threshold": 80, "always_batch_cond_uncond": false, "temp_dir": "", "clean_temp_dir_at_start": true, "ckpt_dir": "E:\\ImageAI\\models", "vae_dir": "E:\\ImageAI\\automatic\\models\\VAE", "embeddings_dir": "E:\\ImageAI\\automatic\\models\\embeddings", "hypernetwork_dir": "E:\\ImageAI\\automatic\\models\\hypernetworks", "codeformer_models_path": "E:\\ImageAI\\automatic\\models\\Codeformer", "gfpgan_models_path": "E:\\ImageAI\\automatic\\models\\GFPGAN", "esrgan_models_path": "E:\\ImageAI\\automatic\\models\\ESRGAN", "bsrgan_models_path": "E:\\ImageAI\\automatic\\models\\BSRGAN", "realesrgan_models_path": "E:\\ImageAI\\automatic\\models\\RealESRGAN", "scunet_models_path": "E:\\ImageAI\\automatic\\models\\ScuNET", "swinir_models_path": "E:\\ImageAI\\automatic\\models\\SwinIR", "ldsr_models_path": "E:\\ImageAI\\automatic\\models\\LDSR", "clip_models_path": "E:\\ImageAI\\automatic\\models\\CLIP", "lora_dir": "E:\\ImageAI\\automatic\\models\\Lora", "lyco_dir": "E:\\ImageAI\\automatic\\models\\LyCORIS", "styles_dir": "styles.csv", "samples_save": true, "samples_format": "jpg", "samples_filename_pattern": "", "save_images_add_number": true, "grid_save": false, "grid_format": "jpg", "grid_extended_filename": true, "grid_only_if_multiple": true, "grid_prevent_empty_spots": true, "n_rows": -1, "save_txt": false, "save_log_fn": "", "save_images_before_face_restoration": true, "save_images_before_highres_fix": true, "save_images_before_color_correction": true, "save_mask": false, "save_mask_composite": false, "jpeg_quality": 85, "webp_lossless": false, "img_max_size_mp": 200, "use_original_name_batch": true, "use_upscaler_name_as_suffix": true, "save_selected_only": true, "save_init_img": false, "save_to_dirs": false, "grid_save_to_dirs": false, "use_save_to_dirs_for_ui": false, "directories_filename_pattern": "[date]", "directories_max_prompt_words": 8, "outdir_samples": "", "outdir_txt2img_samples": "outputs/text", "outdir_img2img_samples": "outputs/image", "outdir_extras_samples": "outputs/extras", "outdir_grids": "", "outdir_txt2img_grids": "outputs/grids", "outdir_img2img_grids": "outputs/grids", "outdir_save": "outputs/save", "outdir_init_images": "outputs/init-images", "memmon_poll_rate": 2, "precision": "Autocast", "cuda_dtype": "FP16", "no_half": false, "no_half_vae": false, "upcast_sampling": false, "disable_nan_check": true, "rollback_vae": false, "opt_channelslast": false, "cudnn_benchmark": false, "cuda_allow_tf32": true, "cuda_allow_tf16_reduced": true, "cuda_compile": false, "cuda_compile_mode": "none", "cuda_compile_verbose": true, "cuda_compile_errors": true, "disable_gc": false, "upscaler_for_img2img": "SwinIR_4x", "realesrgan_enabled_models": ["R-ESRGAN 4x+", "R-ESRGAN 4x+ Anime6B"], "ESRGAN_tile": 192, "ESRGAN_tile_overlap": 8, "SCUNET_tile": 256, "SCUNET_tile_overlap": 8, "use_old_hires_fix_width_height": false, "dont_fix_second_order_samplers_schedule": false, "ldsr_steps": 100, "ldsr_cached": false, "SWIN_tile": 192, "SWIN_tile_overlap": 8, "face_restoration_model": "CodeFormer", "code_former_weight": 0.2, "face_restoration_unload": false, "unload_models_when_training": false, "pin_memory": true, "save_optimizer_state": false, "save_training_settings_to_txt": true, "dataset_filename_word_regex": "", "dataset_filename_join_string": " ", "embeddings_templates_dir": "E:\\ImageAI\\automatic\\train/templates", "training_image_repeats_per_epoch": 1, "training_write_csv_every": 0, "training_enable_tensorboard": false, "training_tensorboard_save_images": false, "training_tensorboard_flush_every": 120, "interrogate_keep_models_in_memory": false, "interrogate_return_ranks": true, "interrogate_clip_num_beams": 1, "interrogate_clip_min_length": 32, "interrogate_clip_max_length": 192, "interrogate_clip_dict_limit": 2048, "interrogate_clip_skip_categories": ["artists", "movements", "flavors"], "interrogate_deepbooru_score_threshold": 0.65, "deepbooru_sort_alpha": false, "deepbooru_use_spaces": false, "deepbooru_escape": true, "deepbooru_filter_tags": "", "extra_networks_default_view": "cards", "extra_networks_default_multiplier": 1.0, "extra_networks_card_width": 0, "extra_networks_card_height": 0, "extra_networks_add_text_separator": " ", "sd_hypernetwork": "None", "sd_lyco": "None", "sd_lora": "None", "gradio_theme": "derekzen/stardust", "return_grid": true, "return_mask": false, "return_mask_composite": false, "disable_weights_auto_swap": true, "send_seed": false, "send_size": true, "font": "", "keyedit_precision_attention": 0.1, "keyedit_precision_extra": 0.05, "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()", "quicksettings": "sd_model_checkpoint,sd_vae,initial_noise_multiplier", "hidden_tabs": ["Vector Studio", "Model Converter", "Train", "System Info"], "ui_tab_reorder": "From Text, From Image, Process Image", "ui_scripts_reorder": "Enable Dynamic Thresholding, ControlNet", "ui_reorder": "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts", "ui_extra_networks_tab_reorder": "", "show_progressbar": true, "live_previews_enable": true, "show_progress_grid": true, "notification_audio_enable": false, "notification_audio_path": "html/notification.mp3", "show_progress_every_n_steps": 2, "show_progress_type": "Approx NN", "live_preview_content": "Combined", "live_preview_refresh_period": 250, "show_samplers": ["Euler", "DPM++ 2M", "DPM++ 2S a Karras", "DPM++ 2S a", "DPM++ SDE Karras", "DPM2 a Karras", "Euler a", "DPM++ 2M Karras", "UniPC", "DPM++ SDE", "DPM2 Karras"], "fallback_sampler": "Euler a", "eta_ancestral": 1.0, "eta_ddim": 0.0, "ddim_discretize": "uniform", "s_churn": 0.0, "s_min_uncond": 0, "s_tmin": 0.0, "s_noise": 1.0, "eta_noise_seed_delta": 31336, "always_discard_next_to_last_sigma": false, "uni_pc_variant": "bh1", "uni_pc_skip_type": "time_uniform", "uni_pc_order": 3, "uni_pc_lower_order_final": true, "token_merging": false, "token_merging_ratio": 0.5, "token_merging_hr_only": true, "token_merging_ratio_hr": 0.5, "token_merging_random": false, "token_merging_merge_attention": true, "token_merging_merge_cross_attention": false, "token_merging_merge_mlp": false, "token_merging_maximum_down_sampling": 1, "token_merging_stride_x": 2, "token_merging_stride_y": 2, "postprocessing_enable_in_main_ui": [], "postprocessing_operation_order": [], "upscaling_max_images_in_cache": 5, "disabled_extensions": [], "disable_all_extensions": "none", "sd_checkpoint_hash": "fee5b0136461cd7c5872214d84723152a1d6af5286e5a91ec21e31e3460c1b58", "aesthetic_scorer_enabled": true, "aesthetic_scorer_clip_model": "ViT-L/14", "control_net_model_config": "models\\cldm_v15.yaml", "control_net_model_adapter_config": "models\\t2iadapter_sketch_sd14v1.yaml", "control_net_detectedmap_dir": "detected_maps", "control_net_models_path": "", "control_net_modules_path": "", "control_net_max_models_num": 5, "control_net_model_cache_size": 1, "control_net_no_detectmap": false, "control_net_detectmap_autosaving": false, "control_net_allow_script_control": false, "control_net_sync_field_args": false, "controlnet_show_batch_images_in_ui": false, "controlnet_increment_seed_during_batch": false, "image_browser_active_tabs": "txt2img, img2img, txt2img-grids, img2img-grids, Extras, Favorites, Others", "image_browser_hidden_components": [], "image_browser_with_subdirs": true, "image_browser_preload": false, "image_browser_copy_image": false, "image_browser_delete_message": true, "image_browser_txt_files": true, "image_browser_debug_level": "0 - none", "image_browser_delete_recycle": false, "image_browser_scan_exif": true, "image_browser_mod_shift": false, "image_browser_mod_ctrl_shift": false, "image_browser_enable_maint": true, "image_browser_ranking_pnginfo": false, "image_browser_page_columns": 6.0, "image_browser_page_rows": 6.0, "image_browser_pages_perload": 20.0, "image_browser_use_thumbnail": false, "image_browser_thumbnail_size": 200.0, "image_browser_swipe": false, "image_browser_img_tooltips": true, "image_browser_scoring_type": "aesthetic_score", "image_browser_show_progress": true, "infzoom_outpath": "outputs", "infzoom_outSUBpath": "infinite-zooms", "infzoom_outsizeW": 512, "infzoom_outsizeH": 512, "infzoom_ffprobepath": "", "infzoom_txt2img_model": null, "infzoom_inpainting_model": null, "infzoom_defPrompt": "{\n        \"prePrompt\": \"Huge spectacular Waterfall in \",\n        \"prompts\": {\n                \"data\": [\n                        [0, \"a dense tropical forest\"],\n                        [2, \"a Lush jungle\"],\n                        [3, \"a Thick rainforest\"],\n                        [5, \"a Verdant canopy\"]\n                ]\n        },\n        \"postPrompt\": \"epic perspective,(vegetation overgrowth:1.3)(intricate, ornamentation:1.1),(baroque:1.1), fantasy, (realistic:1) digital painting , (magical,mystical:1.2) , (wide angle shot:1.4), (landscape composed:1.2)(medieval:1.1),(tropical forest:1.4),(river:1.3) volumetric lighting ,epic, style by Alex Horley Wenjun Lin greg rutkowski Ruan Jia (Wayne Barlowe:1.2)\",\n        \"negPrompt\": \"frames, border, edges, borderline, text, character, duplicate, error, out of frame, watermark, low quality, ugly, deformed, blur, bad-artist\"\n}", "infzoom_collectAllResources": false, "sadtalker_result_dir": "E:\\ImageAI\\automatic\\outputs\\SadTalker", "openpose3d_use_online_version": false, "arh_javascript_aspect_ratio_show": true, "arh_javascript_aspect_ratio": "1:1, 3:2, 4:3, 5:4, 16:9", "arh_ui_javascript_selection_method": "Aspect Ratios Dropdown", "arh_hide_accordion_by_default": false, "arh_expand_by_default": false, "arh_ui_component_order_key": "MaxDimensionScaler, PredefinedAspectRatioButtons, PredefinedPercentageButtons", "arh_show_max_width_or_height": true, "arh_max_width_or_height": 1024, "arh_show_predefined_aspect_ratios": true, "arh_predefined_aspect_ratio_use_max_dim": false, "arh_predefined_aspect_ratios": "1:1, 4:3, 16:9, 9:16, 21:9", "arh_show_predefined_percentages": true, "arh_predefined_percentages": "25, 50, 75, 125, 150, 175, 200", "arh_predefined_percentages_display_key": "Incremental/decremental percentage (-50%, +50%)", "def_img_cfg": "1.5", "training_picker_fixed_size": 512.0, "training_picker_videos_path": "E:\\ImageAI\\automatic\\training-picker\\videos", "training_picker_framesets_path": "E:\\ImageAI\\automatic\\training-picker\\extracted-frames", "training_picker_default_output_path": "E:\\ImageAI\\automatic\\training-picker\\cropped-frames", "dp_ignore_whitespace": false, "dp_write_raw_template": false, "dp_write_prompts_to_file": false, "dp_parser_variant_start": "{", "dp_parser_variant_end": "}", "dp_parser_wildcard_wrap": "__", "dp_limit_jinja_prompts": false, "dp_auto_purge_cache": false, "dp_magicprompt_default_model": "Gustavosta/MagicPrompt-Stable-Diffusion", "dp_magicprompt_batch_size": 1}"]
```

That's all, I see on the console.

**Comment by jfranecki** [comment]
I never once had a problem running this with Vladmandic/automatic until the latest version. Now I can only use Euler a as a sampling method. If I use anything else I get list index out of range.
